In [2]:
import numpy as np

In [2]:
z = np.array([1,1])
print(f"[z] : {z}, shape: {np.shape(z)}") # 1행 2열
print(f"[z.T] : {z.T}, shape: {np.shape(z.T)}") # 2행 1열
reshape_z1 = np.reshape(z, (1, 2)) # 명시적으로 1행 2열 변환
print(f"[reshape_z1] : {reshape_z1}, shape: {np.shape(reshape_z1)}") # 1행 2열
reshape_z2 = np.reshape(z, (1,-1)) # 
print(f"[reshape_z2] : {reshape_z2}, shape: {np.shape(reshape_z2)}") # 1행 2열

print(reshape_z1 == reshape_z2) # True
if np.array_equal(reshape_z1, reshape_z2): # 
    print("reshape_z1 == reshape_z2")
else:
    print("reshape_z1 != reshape_z2")

c = np.reshape(z, (2,1))
print(f"\n[c] : {c}, shape: {np.shape(c)}") # 2행 1열

[z] : [1 1], shape: (2,)
[z.T] : [1 1], shape: (2,)
[reshape_z1] : [[1 1]], shape: (1, 2)
[reshape_z2] : [[1 1]], shape: (1, 2)
[[ True  True]]
reshape_z1 == reshape_z2

[c] : [[1]
 [1]], shape: (2, 1)


In [3]:
x = np.arange(12)# 2행 2열
print(f"[x] : {x}, shape: {np.shape(x)}")

[x] : [ 0  1  2  3  4  5  6  7  8  9 10 11], shape: (12,)


In [4]:
y = np.reshape(x, (3, -1)) # 3행 4열
print(f"\n[y] : {y},\n shape: {np.shape(y)}") # 3행 4열


[y] : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]],
 shape: (3, 4)


In [5]:
z = np.reshape(x, (-1, 2)) # 6행 2열
print(f"\n[z] : {z},\n shape: {np.shape(z)}") # 6행 2열


[z] : [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]],
 shape: (6, 2)


In [7]:
x.shape, x.T.shape

((12,), (12,))

In [40]:
x@x.T

array([[ 5, 14],
       [14, 50]])

In [41]:
x.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [43]:
t = np.zeros(1)
t

array([0.])

In [44]:
t.shape

(1,)

In [49]:
t = np.reshape(t, (1,-1))
t.shape

(1, 1)