In [2]:
import numpy as np


In [3]:

z = np.array([1,1])
print(f"[z] : {z}, shape: {np.shape(z)}") # 1행 2열
print(f"[z.T] : {z.T}, shape: {np.shape(z.T)}") # 2행 1열
reshape_z1 = np.reshape(z, (1, 2)) # 명시적으로 1행 2열 변환
print(f"[reshape_z1] : {reshape_z1}, shape: {np.shape(reshape_z1)}") # 1행 2열
reshape_z2 = np.reshape(z, (1,-1)) # 
print(f"[reshape_z2] : {reshape_z2}, shape: {np.shape(reshape_z2)}") # 1행 2열

print(reshape_z1 == reshape_z2) # True
if np.array_equal(reshape_z1, reshape_z2): # 
    print("reshape_z1 == reshape_z2")
else:
    print("reshape_z1 != reshape_z2")

c = np.reshape(z, (2,1))
print(f"\n[c] : {c}, shape: {np.shape(c)}") # 2행 1열

[z] : [1 1], shape: (2,)
[z.T] : [1 1], shape: (2,)
[reshape_z1] : [[1 1]], shape: (1, 2)
[reshape_z2] : [[1 1]], shape: (1, 2)
[[ True  True]]
reshape_z1 == reshape_z2

[c] : [[1]
 [1]], shape: (2, 1)


In [16]:
x = np.arange(12)# 2행 2열
print(f"[x] : {x}, shape: {np.shape(x)}")

[x] : [ 0  1  2  3  4  5  6  7  8  9 10 11], shape: (12,)


In [ ]:
y = x.reshape(1, -3)
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [18]:
z = x.reshape(-1, 2)
z

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [39]:
x.shape, x.T.shape

((2, 3), (3, 2))

In [40]:
x@x.T

array([[ 5, 14],
       [14, 50]])

In [41]:
x.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [43]:
t = np.zeros(1)
t

array([0.])

In [44]:
t.shape

(1,)

In [49]:
t = np.reshape(t, (1,-1))
t.shape

(1, 1)

In [24]:
# -2, -3, -4 등 다양한 음수 값으로 reshape 테스트
print("원본 배열 x:")
print(x)
print(f"x.shape: {x.shape}")

try:
    print("\nx.reshape(1, -2):")
    print(x.reshape(1, -2))
    print(f"shape: {x.reshape(1, -2).shape}")
except Exception as e:
    print(f"오류: {e}")

try:
    print("\nx.reshape(1, -3):")
    print(x.reshape(1, -3))
    print(f"shape: {x.reshape(1, -3).shape}")
except Exception as e:
    print(f"오류: {e}")
    
try:
    print("\nx.reshape(1, -4):")
    print(x.reshape(1, -4))
    print(f"shape: {x.reshape(1, -4).shape}")
except Exception as e:
    print(f"오류: {e}")

try:
    print("\nx.reshape(-2, 6):")
    print(x.reshape(-2, 6))
    print(f"shape: {x.reshape(-2, 6).shape}")
except Exception as e:
    print(f"오류: {e}")

원본 배열 x:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
x.shape: (12,)

x.reshape(1, -2):
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
shape: (1, 12)

x.reshape(1, -3):
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
shape: (1, 12)

x.reshape(1, -4):
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
shape: (1, 12)

x.reshape(-2, 6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
shape: (2, 6)
